OUTPUT_DIR = "output/"
AUDIO_DIR = OUTPUT_DIR + "audio/"
IMAGE_DIR = OUTPUT_DIR + "images/"
VIDEO_DIR = OUTPUT_DIR + "videos/"
SUBTITLE_DIR = OUTPUT_DIR + "subtitles/"
OTHER_DIR = OUTPUT_DIR + "other/"
ASSETS_DIR = "assets/"
